DOCUMENT_LABELS = [
    "specification",
    "scientific_report",
    "scientific_publication",
    "resume",
    "questionnaire",
    "presentation",
    "news_article",
    "memo",
    "letter",
    "invoice",
    "handwritten",
    "form",
    "file_folder",
    "email",
    "budget",
    "advertisement"
]

DOCUMENT_ENTITIES = {
    "specification": [
        "Title",
        "Date",
        "Specifications",
    ],
    "scientific_report": [
        "Title",
        "Authors",
        "Abstract",
        "Keywords",
        "Introduction",
        "Conclusion",
        "Date"
    ],
    "scientific_publication": [
        "Title",
        "Authors",
        "Abstract",
        "Keywords",
        "Journal Name",
        "Issue",
        "Pages",
        "Publication Date"
    ],
    "resume": [
        "First Name",
        "Last Name",
        "Email",
        "Education",
        "Work Experience",
        "Skills",
        "Certifications",
        "Languages",
    ],
    "questionnaire": [
        "Title",
        "Questionnaire ID",
        "Respondent Name",
        "Date",
        "Questions",
        "Answers",
    ],
    "presentation": [
        "Title",
        "Slide Titles",
        "Key Points",
        "Company/Organization"
    ],
    "news_article": [
        "Headline",
        "Author",
        "Date",
        "Location",
        "Body",
        "Source",
        "Category",
        "Editor",
        "Publisher"
    ],
    "memo": [
        "To",
        "From",
        "Date",
        "Subject",
        "Body",
        "CC"
    ],
    "letter": [
        "Sender Name",
        "Sender Address",
        "Recipient Name",
        "Recipient Address",
        "Date",
        "Subject",
        "Body",
        "Greeting",
    ],
    "invoice": [
        "Invoice Number",
        "Date",
        "Due Date",
        "Bill To",
        "Ship To",
        "Vendor",
        "Items",
        "Description",
        "Quantity",
        "Unit Price",
        "Total Amount",
        "Tax",
        "Payment Terms"
    ],
    "handwritten": [
        "Author Name",
        "Date",
        "Keywords",
        "Text Body",
        "Page Number",
        "Subject",
    ],
    "form": [
        "Form Title",
        "Form ID",
        "Date",
        "Name",
        "Address",
        "Phone Number",
        "Email",
        "Fields",
        "Comments"
    ],
    "file_folder": [
        "Folder Name",
        "Folder ID",
    ],
    "email": [
        "From",
        "To",
        "CC",
        "BCC",
        "Date",
        "Subject",
        "Body",
        "Attachments",
    ],
    "budget": [
        "Budget Title",
        "Project Name",
        "Start Date",
        "End Date",
        "Department",
        "Item",
        "Category",
        "Estimated Cost",
        "Actual Cost",
        "Difference",
        "Total Budget",
        "Responsible Person"
    ],
    "advertisement": [
        "Title",
        "Advertiser",
    ]
}
